server:
  port: 6001
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://ecommerce1:7001/eureka/,http://ecommerce2:7002/eureka/
  instance:
    instance-id: gateway.com
    prefer-ip-address: true
zuul:
  routes:
    user:
      serviceId: provider
      path: /ecommerce/**
  ignored-services: provider
  #  ignored-services: "*"
  prefix: /neu

#  AccessTokenFilter:
#    pre:
#      disable: true
#  AccessTokenFilter1:
#    pre:
#      disable: true
