spring:
  application:
    name: register-center
server:
  port: 7001
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: htpp://localhost:7001/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://ecommerce2:7002/eureka/
  instance:
    prefer-ip-address: false
    hostname: ecommerce1
