server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://ecommerce1:7001/eureka/,http://ecommerce2:7002/eureka/
    register-with-eureka: false
spring:
  application:
    name: consumer