server:
  port: 80
spring:
  application:
    name: feign
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://ecommerce1:7001/eureka/,http://ecommerce2:7002/eureka/
feign:
  hystrix:
    enabled: true